### ISSUE TITLE
[Design discussion] Move event sending into handler return values.

### ISSUE THREAD

**Issue by nyaray** [ScenicFramework/scenic#158]
What if instead of calling `send_event/1`, we returned a list of events, sort of how we return the new Graph to push?

I'm not sure if this is a proper feature request or whatever, but now that graph-pushing has been moved to handler return value it kind of stuck out to me that event sending isn't, if that makes sense. Please go ahead and close this if it's not interesting to discuss (or the wrong place to have that discussion!)

**Comment by nyaray** [comment]
Just to provide a clearer example of what I mean by "returned a list of events"... I'm thinking that `handle_input/2` and others could return something like this:

``` elixir
  def handle_input({:cursor_pos, {x, _y}}, _ctx, state = %State{:tracking => true}) do
    {state, events} = handle_cursor_pos(state, x)
    # match below for illustration purposes, events could look something like:
    [
     {:value_changed, state.id, new_value}, # regular update event
     {:value_high_watermark, state.id} # (optional event, depending on value)
    ] = events
    {:noreply, state, push: state.graph, events: events}
  end
```

This would give visibility to what was going on and encourage a more structured coding style, I think, since it would force you to delegate the event creation to Scenic, instead of calling the send_event function yourself. Something something "prefer data over functions" á la Clojure :)

**Comment by crertel** [comment]
Would this allow an improperly written handler to return an incomplete list of events? Is that a problem with the existing API too?

**Comment by nyaray** [comment]
What do you mean by incomplete list? Did you mean improper list, such as `[1 | 2]`?

The idea is pretty much that the component contract is that components return events in the callback-return value instead of side-effecting by calling the send_event function.

**Comment by crertel** [comment]
Ah, my misunderstanding here may be that I'm confused if the event list is all of the events, or just the ones from the component.

Like, would the function be adding events to the list and passing it upwards, or what?

**Comment by nyaray** [comment]
The event list contains the events generated by the component as a result of the user's input.

**Comment by crertel** [comment]
Thanks for the explanation! That makes a lot more sense--for some reason, I kept thinking about it like middleware.

**Comment by nyaray** [comment]
Hehe, it's like they say... words are hard!

So, any thought about the idea itself? :)

**Comment by nyaray** [comment]
I've been thinking a little more about this and think the change could fit in [here(1)](https://github.com/boydm/scenic/blob/master/lib/scenic/scene.ex#L1474) and that it could be rather straight-forward to iterate over a list of events, doing what [send_event(2)](https://github.com/boydm/scenic/blob/master/lib/scenic/scene.ex#L617) does internally.

(1) - `scene.ex`, `deal_with_response_opts/2` implementation
``` elixir
  defp deal_with_response_opts(opts, state) when is_list(opts) do
    {:ok, state} =
      case opts[:push] do
        %Graph{} = graph -> internal_push_graph(graph, nil, state)
        {%Graph{} = graph, sub_id} -> internal_push_graph(graph, sub_id, state)
        _ -> {:ok, state}
      end

    opts
    |> Keyword.delete(:push)
    |> case do
      [{:timeout, timeout}] -> {timeout, state}
      [{:continue, term}] -> {{:continue, term}, state}
      _ -> {nil, state}
    end
end
```

(2) - `scene.ex`, `send_event/1` implementation
``` elixir
      defp send_event(event_msg) do
        case Process.get(:parent_pid) do
          nil -> {:error, :no_parent}
          pid -> GenServer.cast(pid, {:event, event_msg, self()})
        end
      end
```

Any objections to the general idea, @boydm?

**Comment by boydm** [comment]
Hi! Sorry for the delay.

Here is my reservation. Send_event pushes a message into a process's message box, just like sending any other message via Process.send or the GenServer.* apis.

The developer should probably have explicit control over when those messages are sent and in what order. The nice thing of keeping the send_event api separate instead of passing as a return data is keeping that level of control.

You are right tho that if that is an option, then the `deal_with_response_opts` function would be the right place to put it.

Now that time has passed, how to do you feel about it?

**Comment by nyaray** [comment]
I'm not really sure that I understand your reservation since `send_event` is defined in the `__using__/1-2` macro, which is quite different from the mentioned APIs. I'd argue that exposing `send_event` as a function from `Scene`, instead of defining it inside the mentioned macro, would be more consistent.

> The developer should probably have explicit control over when those messages are sent and in what order. The nice thing of keeping the send_event api separate instead of passing as a return data is keeping that level of control.
> [...]
> Now that time has passed, how to do you feel about it?

Well... you would still retain control of the order, as it is your responsibility to return the event list, ordered however you want, but your point about explicit control over _when_ (especially for inter-event timing) still holds, sort of. One could expand the response opts format to encode if an event is to be dispatched immediately or with a delay: `Scenic` could do a bunch of `:timer.send_after/3` calls when it sees delayed (deferred?) events. If you want to be able to send out events _immediately_, then you must keep `send_event` as it is, though.

With all that said, I, for one, haven't really felt the need to create more than one event that can't wait until the `Scene` handler is done computing the reply/new state. Also, it would make testing easier since you can, given an input, easily see that the handler function returns what it should, for complex cases. I dunno... it just stuck out to me to retain the magic of the macro-defined message sending of `send_event`, while migrating to the cleaner response-opts based `:push` approach... if that makes any sense.

**Comment by crertel** [comment]
Closing as aged-out for now, but if we want to talk about it more just reply to reopen.
