### ISSUE TITLE
Desktop use: Auto-scale

### ISSUE THREAD

**Issue by ShalokShalom** [ScenicFramework/scenic#160]
### What problem does this feature solve?

Hi there. :)

I just see [this video](https://www.youtube.com/watch?v=1QNxLNMq3Uw) and you say at 33:26 that Scenic has no auto-scale solution. 

In the readme on this page, you say Scenic works well with my desktop 

Desktops have different screen sizes. 

### What is your proposed solution?

Add optional auto-scaling.

**Comment by lawik** [comment]
If you build a fixed-size UI, Scenic should be fine for the desktop. You could also write your UI in a way that you calculate your dimensions from the resolution of the device after somehow interrogating the device.

Last I spoke to Boyd I got the feeling that if Scenic gets auto-scaling and that sort of responsiveness it would probably be very basic and that the preferred way would be that there is a contrib library that provides a good auto-scaling solution to the UI framework.

I think he is right too. I think Scenic should be fairly simple but offer great power and people can contribute more opinionated abstractions to implement that sort of featureset. Embedded/Connected devices are a big focus for example and those generally do not have a lot of display sizes to cover and the code for that would be wasteful.

So I agree, it would be incredibly useful. But I believe it is something that should happen from the surrounding ecosystem. Does that make sense to you?

**Comment by ShalokShalom** [comment]
Perfect sense.

**Comment by crertel** [comment]
Closing as aged-out for now, thank you for bringing up the idea!

**Comment by ShalokShalom** [comment]
Aged out in what sense?

**Comment by crertel** [comment]
Well, it hasn't been touched for four years, and it sounds like there may be a workaround for now.

**Comment by ShalokShalom** [comment]
I dont think it is aged out, and I think there was no serious interest in the first place. 
So it might as well stay closed, although I fail to see, why a sensible feature like this would just stop being useful, only because it lacks an implementation. 

Sounds more like wishful thinking, because nobody wants to integrate it.

**Comment by ShalokShalom** [comment]
Can you please tell me about the workaround?
