### ISSUE TITLE
Please push git tags for v0.10.1 and v0.10.2

### ISSUE THREAD

**Issue by axelson** [ScenicFramework/scenic#165]
Is it possible to push a tag for v0.10.1 and v0.10.2? This would be useful when viewing the documentation, right now if you visit a page like: https://hexdocs.pm/scenic/Scenic.Component.Button.html and click on the view source button (in the upper right) it will bring you to a GitHub 404 page: https://github.com/boydm/scenic/blob/v0.10.2/lib/scenic/component/button.ex#L1

**Comment by boydm** [comment]
I’ll take a look soon!
