### ISSUE TITLE
Lootie Files

### ISSUE THREAD

**Issue by pcarvsilva** [ScenicFramework/scenic#238]
Creating animations in code it's really a pain.
Lootie files are a default solution into web developers tool belt and  animators/designers can build it with default animation tools.
Personally i've always thought of Scenic like a Qt approached ecosystem for Elixir especially for Nerves,
since Qt has already created a widget for Lootie, this feature seams really reasonable.

I have a CG background and I was thinking in sending a PR myself, but I could not find any tutorial on how to render a lootie file.

More on Lootie:
https://lottiefiles.com/blog/working-with-lottie/why-use-lottie
https://airbnb.design/lottie/

**Comment by sumanthyedoti** [comment]
I had the same thoughts. It would be a game-changer for scenic if SVGs and Lottie files can be parsed into scenic graphics.

**Comment by crertel** [comment]
I think this is a neat idea, but it's been a couple of years and we still don't really have the animation primitives we might want to support this. Additionally, we'd probably want this functionality as a `scenic_contrib` library and not in core Scenic. Closing for now, but thank you very much for contributing!
