### ISSUE TITLE
Migrate Math module to Elixir's Math module

### ISSUE THREAD

**Issue by pcarvsilva** [ScenicFramework/scenic#246]
https://github.com/folz/math

Matrix operations could be of more use than Scenic

**Comment by crertel** [comment]
Scenic uses a very limited version of matrix math (what you need for graphics), and doesn't implement all the operations one might be interested in. There are other libraries that target more general-purpose usage.

I like the spirit of your suggestion, but I don't think it's practical at this time.

**Comment by crertel** [comment]
Closing old issue; with the Nx stuff it looks like we also sorta kinda have this.
