### ISSUE TITLE
Not receiving input

### ISSUE THREAD

**Issue by marktermaat** [ScenicFramework/scenic#299]
### Problem
The problem is that I can't capture any input in my scene. It's probably me doing something wrong, but I've tried so many things so far, that I'm starting to doubt that it might be an actual bug.

I have a very simple scene:
```elixir
defmodule MyScene.Home do
  use Scenic.Scene
  require Logger

  alias Scenic.Graph

  @graph Graph.build()

  @impl Scenic.Scene
  def init(scene, _param, _opts) do

    scene = push_graph(scene, @graph)

    {:ok, scene}
  end

  def handle_input(event, _context, scene) do
    Logger.info("Received event: #{inspect(event)}")
    {:noreply, scene}
  end
end
```

When I start this, I get a nice window, but no matter what key I hit (even after clicking in or out of the window), it won't give me any input to handle.

### Versions and Environment

Elixir: 1.13.1
Erlang: 24
Scenic: 0.11.0
Scenic driver local: 0.11.0
OS: macOS 12.6

### Steps to reproduce

Try the scene as above (at least on my computer)

### Expected Behavior

Input that is logged

### Actual Behavior

Nothing

**Comment by amclain** [comment]
Have you tried adding a call to [`request_input/2`](https://hexdocs.pm/scenic/Scenic.Scene.html#request_input/2) in `init`? I recall having a similar issue recently and I think that fixed it.

**Comment by marktermaat** [comment]
That does indeed work, thanks! But according to the documentation that shouldn't be necessary, right?
`This is rarely used by scenes and even then mostly for things like key events outside of a text field.`

**Comment by amclain** [comment]
I have a hunch those docs are out of date as of `v0.11`, but @boydm is probably the best person to comment on that.
