### ISSUE TITLE
Stream.delete not deleting the stream

### ISSUE THREAD

**Issue by Geostartico** [ScenicFramework/scenic#323]
### Versions and Environment

Elixir:

```bash
# elixir -v
Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.15.0 (compiled with Erlang/OTP 26)
```

Erlang:

```bash
# erl -v
Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Eshell V14.0.1 (press Ctrl+G to abort, type help(). for help)
```

Scenic:

```text
# mix deps | grep scenic
* scenic 0.11.1 (https://github.com/ScenicFramework/scenic.git) (mix)
* scenic_clock 0.11.0 (https://github.com/ScenicFramework/scenic_clock.git) (mix)
* scenic_driver_local 0.11.0 (https://github.com/ScenicFramework/scenic_driver_local.git) (mix)

```

OS:

```text
EndeavourOS
```

### Steps to reproduce
```
    if(Scenic.Assets.Stream.exists?("loaded_image")) do
      :ok = Scenic.Assets.Stream.delete("loaded_image")
      IO.puts("deleting #{Scenic.Assets.Stream.exists?("loaded_image")}")
    end
```

### Expected Behavior
```
"deleting false"
```
### Actual Behavior
```
'deleting true'
```

### Additional Comments

when trying to insert another stream with the same name as the previous the following error occurs:
```
scenic_driver_local error: "Cannot change image size"
scenic_driver_local puts: "Excess message bytes: 115138"

15:16:54.628 [error] scenic_driver_local: "Cannot change image size"

15:16:54.628 [info] scenic_driver_local: "Excess message bytes: 115138"
scenic_driver_local puts: "message id: 65"

15:16:54.629 [info] scenic_driver_local: "message id: 65"
```
which makes me think that the stream isn't being actually deleted

**Comment by crertel** [comment]
I suspect this is caused because `delete` is [async](https://github.com/ScenicFramework/scenic/blob/391e9d2de4a19ec886f80d1873a0527eafd1b9cf/lib/scenic/assets/stream.ex#L153).

Perhaps if we changed that to a `cast` and forced it to be sync, that'd work?

**Comment by Geostartico** [comment]
I don't think it's the fact it's async, i tried deleting the stream and then waiting some seconds before creating the second one and the problem persists. I'm new to Elixir, what does ```cast``` change exactly?

**Comment by crertel** [comment]
`cast` here says "do this whenever", whereas `call` is "do this synchronously". My first guess is that it's a race thing, but are you saying that you added many seconds of waiting before checking if it exists, right?
