### ISSUE TITLE
Wrongly scaled output on Arch Linux/Wayland

### ISSUE THREAD

**Issue by faebser** [ScenicFramework/scenic#71]
### Checklist

- [x] Check other issues and make sure that it is not reported yet.

### Versions and Environment

Elixir:

```bash
# elixir -v
Erlang/OTP 21 [erts-10.0.8] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
```

Erlang:

```bash
# erl -v
Erlang/OTP 21 [erts-10.0.8] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
```

Scenic:

```text
# mix deps | grep scenic
* scenic_sensor 0.7.0 (Hex package) (mix)
  locked at 0.7.0 (scenic_sensor) a12aed75
* scenic 0.8.0 (Hex package) (mix)
  locked at 0.8.0 (scenic) 44bffa47
* scenic_driver_glfw 0.8.0 (Hex package) (mix)
  locked at 0.8.0 (scenic_driver_glfw) 710e0256
* scenic_clock 0.8.0 (Hex package) (mix)
  locked at 0.8.0 (scenic_clock) fc144430
```

OS:

```text
# uname -a
Arch Linux 4.18.9-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018 x86_64 GNU/Linux
*with wayland*
```

### Steps to reproduce

* install dependencies (I was just missing *community/glfw-wayland 3.2.1-1*)
* generate a new app with mix scenic.new
* run mix deps.get
* run scenic.run

### Expected Behavior

The example app window shows up with correct positioning.

### Actual Behavior

![screenshot from 2018-09-27 16-43-12](https://user-images.githubusercontent.com/333862/46154035-a1b83900-c274-11e8-8494-3593ff7169c8.png)
![screenshot from 2018-09-27 16-34-39](https://user-images.githubusercontent.com/333862/46154038-a250cf80-c274-11e8-8361-28eb68b27817.png)

The rendered output only takes up a quarter of the whole window. The areas for buttons and drop downs are positioned correctly which means to have to click into the empty black part of the window to hit something.

#### Stack Trace

<details>

Sadly there is not a lot to see here, just a single message from GLFW.

```bash
mix scenic.run        
GLFW error 65544: Wayland: Focusing a window requires user interaction
```

</details>

### Additional Comments

* I have a 4k screen, maybe thats a problem?

**Comment by crertel** [comment]
You're on Wayland right?

**Comment by faebser** [comment]
Yes, i am. Arch linux + wayland


On 28 Sep 2018 10:17 p.m., crertel <notifications@github.com> wrote:

You're on Wayland right?

**Comment by Eiji7** [comment]
Probably related:
https://github.com/boydm/scenic_driver_glfw/issues/10

Looks like there are some wrong calls on `glfw` for both `Wayland` and `X11` on `Linux`.

**Comment by Eiji7** [comment]
@boydm Can you please let me know where resize is handled? I'm not sure where I should search it in code … Maybe I could debug it also …

**Comment by boydm** [comment]
OMG. I think I just solved this. Only two years later.

The time I push  an update to the v0.11 branch (hopefully later this week) this issue should be fixed.

**Comment by Eiji7** [comment]
@boydm Yes, I tested and it works now. Many thanks!
